export const products = [
  {
    id: 'prod_P8iZ0FavCCXszX',
    object: 'product',
    active: true,
    attributes: [],
    created: 1701892328,
    default_price: 'price_1OKR8fSE3NqABDdNZjseLoSt',
    description: 'This is an samplet T-Shirt',
    features: [],
    images: [
      'https://files.stripe.com/links/MDB8YWNjdF8xT0tGcmhTRTNOcUFCRGROfGZsX3Rlc3RfWFVVTEtqelBUMnRRUkFidWUwUGFxMGdv00f4KCLR4j',
    ],
    livemode: false,
    metadata: {},
    name: 'T-Shirt',
    package_dimensions: null,
    shippable: null,
    statement_descriptor: null,
    tax_code: null,
    type: 'service',
    unit_label: null,
    updated: 1701892331,
    url: null,
    price: 399,
  },
  {
    id: 'prod_P8iV8L9Or2e7Qa',
    object: 'product',
    active: true,
    attributes: [],
    created: 1701892094,
    default_price: 'price_1OKR4tSE3NqABDdNArCsR3jd',
    description: 'This is an sample Shirt',
    features: [],
    images: [
      'https://files.stripe.com/links/MDB8YWNjdF8xT0tGcmhTRTNOcUFCRGROfGZsX3Rlc3RfTWs1VnFJbWtEdjNZQWNLTXRIVml0d1h400AyQChiBB',
    ],
    livemode: false,
    metadata: {},
    name: 'Shirt',
    package_dimensions: null,
    shippable: null,
    statement_descriptor: null,
    tax_code: null,
    type: 'service',
    unit_label: null,
    updated: 1701892097,
    url: null,
    price: 298,
  },
];
